variables:
  DX01_VERSION: "V2.3"

stages:
  - build

build_dx01:
  stage: build
  tags:
    - windows

  script:
    - cd DX01_ShortCircuitTester
    - dotnet nuget locals all --clear
    - dotnet restore DX01_ShortCircuitTester.sln --force
    - '& "C:\Program Files\Microsoft Visual Studio\18\Insiders\MSBuild\Current\Bin\MSBuild.exe" DX01_ShortCircuitTester.sln'

  artifacts:
    name: "DX01_${DX01_VERSION}"
    when: always
    paths:
      - DX01_ShortCircuitTester/**/bin/Debug/net48/
    expire_in: 7 days
