stages:
  - build

build_dx01:
  stage: build
  tags:
    - windows

  script:
    - cd DX01_ShortCircuitTester
    - '& "C:\Program Files\Microsoft Visual Studio\18\Insiders\MSBuild\Current\Bin\MSBuild.exe" DX01_ShortCircuitTester.sln'
