stages:
  - prepare
  - build

get_version:
  stage: prepare
  tags:
    - windows

  script:
    - Write-Host "===== CURRENT PATH ====="
    - Get-Location
    - Write-Host "===== ROOT FILES ====="
    - Get-ChildItem
    - Write-Host "===== FIND CSPROJ ====="
    - Get-ChildItem -Recurse -Filter *.csproj | Select-Object FullName

build:
  stage: build
  tags:
    - windows
  needs:
    - job: get_version
      artifacts: true
  script:
    - echo DX01_VERSION=%DX01_VERSION%
    - nuget restore DX01_ShortCircuitTester.sln
    - msbuild DX01_ShortCircuitTester.sln /p:Configuration=Release
  artifacts:
    name: "DTX01_${DX01_VERSION}"
    paths:
      - DX01_ShortCircuitTester/bin/Release/
    expire_in: 7 days