name: Build DX01

on:
  push:
  workflow_dispatch:
  
permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2
      # ↓↓↓ 新增這段(版號名稱) ↓↓↓ 
      - name: Read Version
        shell: pwsh
        run: |
          [xml]$xml = Get-Content "DX01_ShortCircuitTester/DX01_ShortCircuitTester/DX01_ShortCircuitTester.csproj"
          $version = $xml.Project.PropertyGroup.Version
          echo "VERSION=V$version" >> $env:GITHUB_ENV
      - name: Show Version
        run: echo ${{ env.VERSION }}

      - name: Restore NuGet
        run: nuget restore DX01_ShortCircuitTester/DX01_ShortCircuitTester.sln

      - name: Build Release
        run: msbuild DX01_ShortCircuitTester/DX01_ShortCircuitTester.sln /p:Configuration=Release

      - name: Create ZIP
        shell: pwsh
        run: |
          Compress-Archive `
            -Path "DX01_ShortCircuitTester/DX01_ShortCircuitTester/bin/Release/*" `
            -DestinationPath "DTX01_${{ env.VERSION }}.zip" `
            -Force
      
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: DTX01_${{ env.VERSION }}
          path: DTX01_${{ env.VERSION }}.zip
          
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.VERSION }}
          name: DTX01_${{ env.VERSION }}
          files: DTX01_${{ env.VERSION }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
